include(${CMAKE_CURRENT_LIST_DIR}/cmake/RohrExample.cmake)

add_subdirectory(engine-core/view-port ${CMAKE_BINARY_DIR}/examples/engine-core/view-port/build)
add_subdirectory(engine-core/flies-in-pit ${CMAKE_BINARY_DIR}/examples/engine-core/flies-in-pit/build)
add_subdirectory(engine-core/flies-around-ball ${CMAKE_BINARY_DIR}/examples/engine-core/flies-around-ball/build)
add_subdirectory(engine-core/fly-to-finish ${CMAKE_BINARY_DIR}/examples/engine-core/fly-to-finish/build)
add_subdirectory(engine-core/game-state ${CMAKE_BINARY_DIR}/examples/engine-core/game-state/build)
add_subdirectory(engine-core/user-interface ${CMAKE_BINARY_DIR}/examples/engine-core/user-interface/build)
add_subdirectory(engine-core/joints ${CMAKE_BINARY_DIR}/examples/engine-core/joints/build)
add_subdirectory(engine-core/soft-body ${CMAKE_BINARY_DIR}/examples/engine-core/soft-body/build)
add_subdirectory(editor/basic-editor ${CMAKE_BINARY_DIR}/examples/editor/basic-editor/build)
add_subdirectory(editor/pong ${CMAKE_BINARY_DIR}/examples/editor/pong/build)
