#ifndef ROHR_EDITOR_NOTIFICATION_LAYOUT_H
#define ROHR_EDITOR_NOTIFICATION_LAYOUT_H

#define EDITOR_NOTIFICATION_LEFT 14.0f
#define EDITOR_NOTIFICATION_BOTTOM 14.0f
#define EDITOR_NOTIFICATION_WIDTH 190.0f
#define EDITOR_NOTIFICATION_LOG_HEIGHT 28.0f
#define EDITOR_NOTIFICATION_TOAST_HEIGHT 34.0f
#define EDITOR_NOTIFICATION_TOAST_GAP 6.0f
#define EDITOR_NOTIFICATION_TOAST_DISMISS_SIZE 16.0f
#define EDITOR_NOTIFICATION_TOAST_DISMISS_INSET 2.0f
#define EDITOR_NOTIFICATION_LOG_ROW_HEIGHT 38.0f
#define EDITOR_NOTIFICATION_LOG_ROW_BUTTON_HEIGHT 32.0f
#define EDITOR_NOTIFICATION_SCROLL_STEP 38.0f
#define EDITOR_NOTIFICATION_TOAST_LIFETIME_MS 10000ULL

#endif
