#ifndef ROHR_EDITOR_LAYOUT_H
#define ROHR_EDITOR_LAYOUT_H

#include "rohr.h"

#define EDITOR_VIEWPORT_WIDTH (WINDOW_WIDTH * 0.8f)
#define EDITOR_TOOLS_WIDTH (WINDOW_WIDTH - EDITOR_VIEWPORT_WIDTH)

#endif
